server:
  port: 8080
  # error:
  #   whitelabel:
  #     enabled: false
  #   include-exception: true
  #   include-stacktrace: never
  #   include-message: always

spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  web:
    resources:
      add-mappings: false

  application:
    name: todolist
  
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
    config-location: classpath:mybatis-config.xml

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    cache: false

  logging:
    level:
      kr.co.mini.todolist.dao: DEBUG
      org.mybatis: DEBUG